const std = @import("std");
const cross_deps = @import("SDL-cross-deps");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const linkage = b.option(
        std.builtin.LinkMode,
        "linkage",
        "Build as a shared (dynamic) or static library",
    ) orelse .dynamic;
    const emit_build_config_h = b.option(
        bool,
        "emit_build_config_h",
        "Also install 'SDL_build_config.h' (for debugging)",
    ) orelse false;

    const version: std.SemanticVersion = .{ .major = 3, .minor = 1, .patch = 2 };
    const windows = target.result.os.tag == .windows;
    const linux = !windows;

    const cross_deps_dep = b.dependencyFromBuildZig(cross_deps, .{});

    const build_config_h = addBuildConfigH(b, target);
    const revision_h = addRevisionH(b, version);

    const sdl3_lib: *std.Build.Step.Compile = switch (linkage) {
        inline else => |x| switch (x) {
            .dynamic => std.Build.addSharedLibrary,
            .static => std.Build.addStaticLibrary,
        }(b, .{
            .name = "SDL3",
            .version = version,
            .target = target,
            .optimize = optimize,
        }),
    };
    const sdl3_mod = &sdl3_lib.root_module;

    sdl3_mod.addCMacro("USING_GENERATED_CONFIG_H", "");
    if (linkage == .static) {
        sdl3_mod.addCMacro("SDL_STATIC_LIB", "");
    }
    sdl3_mod.addCMacro("SDL_BUILD_MAJOR_VERSION", b.fmt("{}", .{version.major}));
    sdl3_mod.addCMacro("SDL_BUILD_MINOR_VERSION", b.fmt("{}", .{version.minor}));
    sdl3_mod.addCMacro("SDL_BUILD_MICRO_VERSION", b.fmt("{}", .{version.patch}));
    if (linkage == .dynamic) {
        sdl3_mod.addCMacro("DLL_EXPORT", "");
    }

    sdl3_mod.addConfigHeader(build_config_h);
    sdl3_mod.addConfigHeader(revision_h);
    sdl3_mod.addIncludePath(b.path("include"));
    sdl3_mod.addIncludePath(b.path("src"));
    sdl3_mod.addSystemIncludePath(cross_deps_dep.path("opengl/include"));
    sdl3_mod.addSystemIncludePath(cross_deps_dep.path("vulkan/include"));
    if (linux) {
        sdl3_mod.addSystemIncludePath(cross_deps_dep.path("wayland/include"));
        sdl3_mod.addIncludePath(cross_deps_dep.path("wayland/src"));
        sdl3_mod.addSystemIncludePath(cross_deps_dep.path("x11/include"));
        sdl3_mod.addSystemIncludePath(cross_deps_dep.path("kmsdrm/include"));
        sdl3_mod.addSystemIncludePath(cross_deps_dep.path("libusb/include"));
        sdl3_mod.addSystemIncludePath(cross_deps_dep.path("pulseaudio/include"));
        sdl3_mod.addSystemIncludePath(cross_deps_dep.path("pipewire/include"));
        sdl3_mod.addSystemIncludePath(cross_deps_dep.path("alsa/include"));
        sdl3_mod.addSystemIncludePath(cross_deps_dep.path("sndio/include"));
        sdl3_mod.addSystemIncludePath(cross_deps_dep.path("jack/include"));
        sdl3_mod.addSystemIncludePath(cross_deps_dep.path("linuxcore/include"));
    }

    if (windows) {
        sdl3_mod.addCSourceFiles(.{ .files = &windows_c_files, .flags = &c_flags });
        if (linkage == .dynamic) {
            sdl3_mod.addWin32ResourceFile(.{ .file = b.path("src/core/windows/version.rc") });
        }
    }
    if (linux) {
        sdl3_mod.addCSourceFiles(.{ .files = &linux_c_files, .flags = &c_flags });
        sdl3_mod.addCSourceFiles(.{
            .root = cross_deps_dep.path("wayland"),
            .files = &cross_deps.wayland_c_files,
            .flags = &c_flags,
        });
    }

    if (windows) {
        sdl3_mod.linkSystemLibrary("m", .{});
        sdl3_mod.linkSystemLibrary("kernel32", .{});
        sdl3_mod.linkSystemLibrary("user32", .{});
        sdl3_mod.linkSystemLibrary("gdi32", .{});
        sdl3_mod.linkSystemLibrary("winmm", .{});
        sdl3_mod.linkSystemLibrary("imm32", .{});
        sdl3_mod.linkSystemLibrary("ole32", .{});
        sdl3_mod.linkSystemLibrary("oleaut32", .{});
        sdl3_mod.linkSystemLibrary("version", .{});
        sdl3_mod.linkSystemLibrary("uuid", .{});
        sdl3_mod.linkSystemLibrary("advapi32", .{});
        sdl3_mod.linkSystemLibrary("setupapi", .{});
        sdl3_mod.linkSystemLibrary("shell32", .{});
        sdl3_mod.linkSystemLibrary("dinput8", .{});
    }
    if (linux) {
        sdl3_mod.linkSystemLibrary("m", .{});
        sdl3_mod.linkSystemLibrary("pthread", .{});
    }
    if (linkage == .dynamic) {
        sdl3_lib.setVersionScript(b.path("src/dynapi/SDL_dynapi.sym"));
        sdl3_lib.linker_allow_undefined_version = true;
    }

    sdl3_lib.installHeadersDirectory(b.path("include"), "", .{ .include_extensions = &installed_headers });
    sdl3_lib.installConfigHeader(revision_h);
    if (emit_build_config_h) {
        sdl3_lib.installConfigHeader(build_config_h);
    }

    const install_sdl3_lib = b.addInstallArtifact(sdl3_lib, .{});

    const install_sdl3 = b.step("install-SDL3", "Install SDL3");
    install_sdl3.dependOn(&install_sdl3_lib.step);

    b.getInstallStep().dependOn(&install_sdl3_lib.step);
}

fn addBuildConfigH(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
) *std.Build.Step.ConfigHeader {
    const windows = target.result.os.tag == .windows;
    const linux = !windows;
    const cpu = target.result.cpu;
    const x86 = cpu.arch.isX86();
    const arm = cpu.arch.isArmOrThumb();
    const aarch64 = cpu.arch.isAARCH64();
    const loongarch = cpu.arch == .loongarch32 or cpu.arch == .loongarch64;
    return b.addConfigHeader(.{
        .style = .{ .cmake = b.path("include/build_config/SDL_build_config.h.cmake") },
        .include_path = "build_config/SDL_build_config.h",
    }, .{
        .HAVE_GCC_ATOMICS = windows or linux,
        .HAVE_GCC_SYNC_LOCK_TEST_AND_SET = false,
        .SDL_DISABLE_ALLOCA = false,
        .HAVE_LIBC = windows or linux,
        .HAVE_ALLOCA_H = linux,
        .HAVE_FLOAT_H = windows or linux,
        .HAVE_ICONV_H = linux,
        .HAVE_INTTYPES_H = windows or linux,
        .HAVE_LIMITS_H = windows or linux,
        .HAVE_MALLOC_H = windows or linux,
        .HAVE_MATH_H = windows or linux,
        .HAVE_MEMORY_H = windows or linux,
        .HAVE_SIGNAL_H = windows or linux,
        .HAVE_STDARG_H = windows or linux,
        .HAVE_STDDEF_H = windows or linux,
        .HAVE_STDINT_H = windows or linux,
        .HAVE_STDIO_H = windows or linux,
        .HAVE_STDLIB_H = windows or linux,
        .HAVE_STRINGS_H = windows or linux,
        .HAVE_STRING_H = windows or linux,
        .HAVE_SYS_TYPES_H = windows or linux,
        .HAVE_WCHAR_H = windows or linux,
        .HAVE_PTHREAD_NP_H = false,
        .HAVE_DLOPEN = linux,
        .HAVE_MALLOC = windows or linux,
        .HAVE_CALLOC = windows or linux,
        .HAVE_REALLOC = windows or linux,
        .HAVE_FREE = windows or linux,
        .HAVE_GETENV = windows or linux,
        .HAVE_SETENV = linux,
        .HAVE_PUTENV = windows or linux,
        .HAVE_UNSETENV = linux,
        .HAVE_ABS = windows or linux,
        .HAVE_BCOPY = linux,
        .HAVE_MEMSET = windows or linux,
        .HAVE_MEMCPY = windows or linux,
        .HAVE_MEMMOVE = windows or linux,
        .HAVE_MEMCMP = windows or linux,
        .HAVE_WCSLEN = windows or linux,
        .HAVE_WCSNLEN = windows or linux,
        .HAVE_WCSLCPY = false,
        .HAVE_WCSLCAT = false,
        .HAVE__WCSDUP = windows,
        .HAVE_WCSDUP = windows or linux,
        .HAVE_WCSSTR = windows or linux,
        .HAVE_WCSCMP = windows or linux,
        .HAVE_WCSNCMP = windows or linux,
        .HAVE_WCSTOL = windows or linux,
        .HAVE_STRLEN = windows or linux,
        .HAVE_STRNLEN = windows or linux,
        .HAVE_STRLCPY = false,
        .HAVE_STRLCAT = false,
        .HAVE__STRREV = windows,
        .HAVE__STRUPR = false,
        .HAVE__STRLWR = false,
        .HAVE_INDEX = linux,
        .HAVE_RINDEX = linux,
        .HAVE_STRCHR = windows or linux,
        .HAVE_STRRCHR = windows or linux,
        .HAVE_STRSTR = windows or linux,
        .HAVE_STRNSTR = false,
        .HAVE_STRTOK_R = windows or linux,
        .HAVE_ITOA = windows,
        .HAVE__LTOA = windows,
        .HAVE__UITOA = false,
        .HAVE__ULTOA = windows,
        .HAVE_STRTOL = windows or linux,
        .HAVE_STRTOUL = windows or linux,
        .HAVE__I64TOA = windows,
        .HAVE__UI64TOA = windows,
        .HAVE_STRTOLL = windows or linux,
        .HAVE_STRTOULL = windows or linux,
        .HAVE_STRTOD = windows or linux,
        .HAVE_ATOI = windows or linux,
        .HAVE_ATOF = windows or linux,
        .HAVE_STRCMP = windows or linux,
        .HAVE_STRNCMP = windows or linux,
        .HAVE_STRCASESTR = linux,
        .HAVE_SSCANF = windows or linux,
        .HAVE_VSSCANF = windows or linux,
        .HAVE_VSNPRINTF = windows or linux,
        .HAVE_ACOS = windows or linux,
        .HAVE_ACOSF = windows or linux,
        .HAVE_ASIN = windows or linux,
        .HAVE_ASINF = windows or linux,
        .HAVE_ATAN = windows or linux,
        .HAVE_ATANF = windows or linux,
        .HAVE_ATAN2 = windows or linux,
        .HAVE_ATAN2F = windows or linux,
        .HAVE_CEIL = windows or linux,
        .HAVE_CEILF = windows or linux,
        .HAVE_COPYSIGN = windows or linux,
        .HAVE_COPYSIGNF = windows or linux,
        .HAVE_COS = windows or linux,
        .HAVE_COSF = windows or linux,
        .HAVE_EXP = windows or linux,
        .HAVE_EXPF = windows or linux,
        .HAVE_FABS = windows or linux,
        .HAVE_FABSF = windows or linux,
        .HAVE_FLOOR = windows or linux,
        .HAVE_FLOORF = windows or linux,
        .HAVE_FMOD = windows or linux,
        .HAVE_FMODF = windows or linux,
        .HAVE_LOG = windows or linux,
        .HAVE_LOGF = windows or linux,
        .HAVE_LOG10 = windows or linux,
        .HAVE_LOG10F = windows or linux,
        .HAVE_LROUND = windows or linux,
        .HAVE_LROUNDF = windows or linux,
        .HAVE_MODF = windows or linux,
        .HAVE_MODFF = windows or linux,
        .HAVE_POW = windows or linux,
        .HAVE_POWF = windows or linux,
        .HAVE_ROUND = windows or linux,
        .HAVE_ROUNDF = windows or linux,
        .HAVE_SCALBN = windows or linux,
        .HAVE_SCALBNF = windows or linux,
        .HAVE_SIN = windows or linux,
        .HAVE_SINF = windows or linux,
        .HAVE_SQRT = windows or linux,
        .HAVE_SQRTF = windows or linux,
        .HAVE_TAN = windows or linux,
        .HAVE_TANF = windows or linux,
        .HAVE_TRUNC = windows or linux,
        .HAVE_TRUNCF = windows or linux,
        .HAVE_FOPEN64 = windows or linux,
        .HAVE_FSEEKO = windows or linux,
        .HAVE_FSEEKO64 = windows or linux,
        .HAVE_MEMFD_CREATE = linux,
        .HAVE_POSIX_FALLOCATE = linux,
        .HAVE_SIGACTION = linux,
        .HAVE_SA_SIGACTION = linux,
        .HAVE_ST_MTIM = linux,
        .HAVE_SETJMP = linux,
        .HAVE_NANOSLEEP = linux,
        .HAVE_GMTIME_R = linux,
        .HAVE_LOCALTIME_R = linux,
        .HAVE_NL_LANGINFO = linux,
        .HAVE_SYSCONF = linux,
        .HAVE_SYSCTLBYNAME = false,
        .HAVE_CLOCK_GETTIME = linux,
        .HAVE_GETPAGESIZE = linux,
        .HAVE_ICONV = linux,
        .SDL_USE_LIBICONV = false,
        .HAVE_PTHREAD_SETNAME_NP = linux,
        .HAVE_PTHREAD_SET_NAME_NP = false,
        .HAVE_SEM_TIMEDWAIT = linux,
        .HAVE_GETAUXVAL = linux,
        .HAVE_ELF_AUX_INFO = false,
        .HAVE_POLL = linux,
        .HAVE__EXIT = windows or linux,
        .HAVE_DBUS_DBUS_H = linux,
        .HAVE_FCITX = linux,
        .HAVE_IBUS_IBUS_H = linux,
        .HAVE_SYS_INOTIFY_H = linux,
        .HAVE_INOTIFY_INIT = linux,
        .HAVE_INOTIFY_INIT1 = linux,
        .HAVE_INOTIFY = linux,
        .HAVE_LIBUSB = linux,
        .HAVE_O_CLOEXEC = linux,
        .HAVE_LINUX_INPUT_H = linux,
        .HAVE_LIBUDEV_H = linux,
        .HAVE_LIBDECOR_H = linux,
        .HAVE_D3D_H = windows,
        .HAVE_D3D11_H = windows,
        .HAVE_D3D12_H = windows,
        .HAVE_DDRAW_H = windows,
        .HAVE_DSOUND_H = windows,
        .HAVE_DINPUT_H = windows,
        .HAVE_XINPUT_H = windows,
        .HAVE_WINDOWS_GAMING_INPUT_H = windows,
        .HAVE_DXGI_H = windows,
        .HAVE_MMDEVICEAPI_H = windows,
        .HAVE_AUDIOCLIENT_H = windows,
        .HAVE_TPCSHRD_H = windows,
        .HAVE_SENSORSAPI_H = windows,
        .HAVE_ROAPI_H = windows,
        .HAVE_SHELLSCALINGAPI_H = windows,
        .USE_POSIX_SPAWN = false,
        .SDL_DEFAULT_ASSERT_LEVEL_CONFIGURED = false,
        .SDL_DEFAULT_ASSERT_LEVEL = null,
        .SDL_AUDIO_DISABLED = false,
        .SDL_JOYSTICK_DISABLED = false,
        .SDL_HAPTIC_DISABLED = false,
        .SDL_HIDAPI_DISABLED = false,
        .SDL_SENSOR_DISABLED = false,
        .SDL_RENDER_DISABLED = false,
        .SDL_THREADS_DISABLED = false,
        .SDL_VIDEO_DISABLED = false,
        .SDL_POWER_DISABLED = false,
        .SDL_CAMERA_DISABLED = false,
        .SDL_AUDIO_DRIVER_ALSA = linux,
        .SDL_AUDIO_DRIVER_ALSA_DYNAMIC = if (linux) "\"" ++ cross_deps.alsa_soname ++ "\"" else "",
        .SDL_AUDIO_DRIVER_ANDROID = false,
        .SDL_AUDIO_DRIVER_OPENSLES = false,
        .SDL_AUDIO_DRIVER_AAUDIO = false,
        .SDL_AUDIO_DRIVER_COREAUDIO = false,
        .SDL_AUDIO_DRIVER_DISK = windows or linux,
        .SDL_AUDIO_DRIVER_DSOUND = windows,
        .SDL_AUDIO_DRIVER_DUMMY = windows or linux,
        .SDL_AUDIO_DRIVER_EMSCRIPTEN = false,
        .SDL_AUDIO_DRIVER_HAIKU = false,
        .SDL_AUDIO_DRIVER_JACK = linux,
        .SDL_AUDIO_DRIVER_JACK_DYNAMIC = if (linux) "\"" ++ cross_deps.jack_soname ++ "\"" else "",
        .SDL_AUDIO_DRIVER_NETBSD = false,
        .SDL_AUDIO_DRIVER_OSS = false,
        .SDL_AUDIO_DRIVER_PIPEWIRE = linux,
        .SDL_AUDIO_DRIVER_PIPEWIRE_DYNAMIC = if (linux) "\"" ++ cross_deps.pipewire_soname ++ "\"" else "",
        .SDL_AUDIO_DRIVER_PULSEAUDIO = linux,
        .SDL_AUDIO_DRIVER_PULSEAUDIO_DYNAMIC = if (linux) "\"" ++ cross_deps.pulseaudio_soname ++ "\"" else "",
        .SDL_AUDIO_DRIVER_SNDIO = linux,
        .SDL_AUDIO_DRIVER_SNDIO_DYNAMIC = if (linux) "\"" ++ cross_deps.sndio_soname ++ "\"" else "",
        .SDL_AUDIO_DRIVER_WASAPI = windows,
        .SDL_AUDIO_DRIVER_VITA = false,
        .SDL_AUDIO_DRIVER_PSP = false,
        .SDL_AUDIO_DRIVER_PS2 = false,
        .SDL_AUDIO_DRIVER_N3DS = false,
        .SDL_AUDIO_DRIVER_QNX = false,
        .SDL_INPUT_LINUXEV = linux,
        .SDL_INPUT_LINUXKD = linux,
        .SDL_INPUT_FBSDKBIO = false,
        .SDL_INPUT_WSCONS = false,
        .SDL_JOYSTICK_ANDROID = false,
        .SDL_JOYSTICK_HAIKU = false,
        .SDL_JOYSTICK_WGI = windows,
        .SDL_JOYSTICK_DINPUT = windows,
        .SDL_JOYSTICK_XINPUT = windows,
        .SDL_JOYSTICK_DUMMY = false,
        .SDL_JOYSTICK_IOKIT = false,
        .SDL_JOYSTICK_MFI = false,
        .SDL_JOYSTICK_LINUX = linux,
        .SDL_JOYSTICK_USBHID = false,
        .SDL_HAVE_MACHINE_JOYSTICK_H = false,
        .SDL_JOYSTICK_HIDAPI = windows or linux,
        .SDL_JOYSTICK_RAWINPUT = windows,
        .SDL_JOYSTICK_EMSCRIPTEN = false,
        .SDL_JOYSTICK_VIRTUAL = windows or linux,
        .SDL_JOYSTICK_VITA = false,
        .SDL_JOYSTICK_PSP = false,
        .SDL_JOYSTICK_PS2 = false,
        .SDL_JOYSTICK_N3DS = false,
        .SDL_HAPTIC_DUMMY = false,
        .SDL_HAPTIC_LINUX = linux,
        .SDL_HAPTIC_IOKIT = false,
        .SDL_HAPTIC_DINPUT = windows,
        .SDL_HAPTIC_ANDROID = false,
        .SDL_LIBUSB_DYNAMIC = if (linux) "\"" ++ cross_deps.libusb_soname ++ "\"" else "",
        .SDL_UDEV_DYNAMIC = if (linux) "\"" ++ cross_deps.libudev_soname ++ "\"" else "",
        .SDL_SENSOR_ANDROID = false,
        .SDL_SENSOR_COREMOTION = false,
        .SDL_SENSOR_WINDOWS = windows,
        .SDL_SENSOR_DUMMY = linux,
        .SDL_SENSOR_VITA = false,
        .SDL_SENSOR_N3DS = false,
        .SDL_LOADSO_DLOPEN = linux,
        .SDL_LOADSO_DUMMY = false,
        .SDL_LOADSO_LDG = false,
        .SDL_LOADSO_WINDOWS = windows,
        .SDL_THREAD_GENERIC_COND_SUFFIX = windows,
        .SDL_THREAD_GENERIC_RWLOCK_SUFFIX = windows,
        .SDL_THREAD_PTHREAD = linux,
        .SDL_THREAD_PTHREAD_RECURSIVE_MUTEX = linux,
        .SDL_THREAD_PTHREAD_RECURSIVE_MUTEX_NP = false,
        .SDL_THREAD_WINDOWS = windows,
        .SDL_THREAD_VITA = false,
        .SDL_THREAD_PSP = false,
        .SDL_THREAD_PS2 = false,
        .SDL_THREAD_N3DS = false,
        .SDL_TIME_UNIX = linux,
        .SDL_TIME_WINDOWS = windows,
        .SDL_TIME_VITA = false,
        .SDL_TIME_PSP = false,
        .SDL_TIME_PS2 = false,
        .SDL_TIME_N3DS = false,
        .SDL_TIMER_HAIKU = false,
        .SDL_TIMER_DUMMY = false,
        .SDL_TIMER_UNIX = linux,
        .SDL_TIMER_WINDOWS = windows,
        .SDL_TIMER_VITA = false,
        .SDL_TIMER_PSP = false,
        .SDL_TIMER_PS2 = false,
        .SDL_TIMER_N3DS = false,
        .SDL_VIDEO_DRIVER_ANDROID = false,
        .SDL_VIDEO_DRIVER_COCOA = false,
        .SDL_VIDEO_DRIVER_DUMMY = windows or linux,
        .SDL_VIDEO_DRIVER_EMSCRIPTEN = false,
        .SDL_VIDEO_DRIVER_HAIKU = false,
        .SDL_VIDEO_DRIVER_KMSDRM = linux,
        .SDL_VIDEO_DRIVER_KMSDRM_DYNAMIC = if (linux) "\"" ++ cross_deps.drm_soname ++ "\"" else "",
        .SDL_VIDEO_DRIVER_KMSDRM_DYNAMIC_GBM = if (linux) "\"" ++ cross_deps.gbm_soname ++ "\"" else "",
        .SDL_VIDEO_DRIVER_N3DS = false,
        .SDL_VIDEO_DRIVER_OFFSCREEN = windows or linux,
        .SDL_VIDEO_DRIVER_PS2 = false,
        .SDL_VIDEO_DRIVER_PSP = false,
        .SDL_VIDEO_DRIVER_RISCOS = false,
        .SDL_VIDEO_DRIVER_ROCKCHIP = false,
        .SDL_VIDEO_DRIVER_RPI = false,
        .SDL_VIDEO_DRIVER_UIKIT = false,
        .SDL_VIDEO_DRIVER_VITA = false,
        .SDL_VIDEO_DRIVER_VIVANTE = false,
        .SDL_VIDEO_DRIVER_VIVANTE_VDK = false,
        .SDL_VIDEO_DRIVER_WAYLAND = linux,
        .SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC = if (linux) "\"" ++ cross_deps.wayland_client_soname ++ "\"" else "",
        .SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_CURSOR = if (linux) "\"" ++ cross_deps.wayland_cursor_soname ++ "\"" else "",
        .SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_EGL = if (linux) "\"" ++ cross_deps.wayland_egl_soname ++ "\"" else "",
        .SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_LIBDECOR = if (linux) "\"" ++ cross_deps.libdecor_soname ++ "\"" else "",
        .SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_XKBCOMMON = if (linux) "\"" ++ cross_deps.xkbcommon_soname ++ "\"" else "",
        .SDL_VIDEO_DRIVER_WINDOWS = windows,
        .SDL_VIDEO_DRIVER_WINRT = false,
        .SDL_VIDEO_DRIVER_X11 = linux,
        .SDL_VIDEO_DRIVER_X11_DYNAMIC = if (linux) "\"" ++ cross_deps.x11_soname ++ "\"" else "",
        .SDL_VIDEO_DRIVER_X11_DYNAMIC_XCURSOR = if (linux) "\"" ++ cross_deps.xcursor_soname ++ "\"" else "",
        .SDL_VIDEO_DRIVER_X11_DYNAMIC_XEXT = if (linux) "\"" ++ cross_deps.xext_soname ++ "\"" else "",
        .SDL_VIDEO_DRIVER_X11_DYNAMIC_XFIXES = if (linux) "\"" ++ cross_deps.xfixes_soname ++ "\"" else "",
        .SDL_VIDEO_DRIVER_X11_DYNAMIC_XINPUT2 = if (linux) "\"" ++ cross_deps.xi_soname ++ "\"" else "",
        .SDL_VIDEO_DRIVER_X11_DYNAMIC_XRANDR = if (linux) "\"" ++ cross_deps.xrandr_soname ++ "\"" else "",
        .SDL_VIDEO_DRIVER_X11_DYNAMIC_XSS = if (linux) "\"" ++ cross_deps.xss_soname ++ "\"" else "",
        .SDL_VIDEO_DRIVER_X11_HAS_XKBKEYCODETOKEYSYM = linux,
        .SDL_VIDEO_DRIVER_X11_SUPPORTS_GENERIC_EVENTS = linux,
        .SDL_VIDEO_DRIVER_X11_XCURSOR = linux,
        .SDL_VIDEO_DRIVER_X11_XDBE = linux,
        .SDL_VIDEO_DRIVER_X11_XFIXES = linux,
        .SDL_VIDEO_DRIVER_X11_XINPUT2 = linux,
        .SDL_VIDEO_DRIVER_X11_XINPUT2_SUPPORTS_MULTITOUCH = linux,
        .SDL_VIDEO_DRIVER_X11_XRANDR = linux,
        .SDL_VIDEO_DRIVER_X11_XSCRNSAVER = linux,
        .SDL_VIDEO_DRIVER_X11_XSHAPE = linux,
        .SDL_VIDEO_DRIVER_QNX = false,
        .SDL_VIDEO_RENDER_D3D = windows,
        .SDL_VIDEO_RENDER_D3D11 = windows,
        .SDL_VIDEO_RENDER_D3D12 = windows,
        .SDL_VIDEO_RENDER_METAL = false,
        .SDL_VIDEO_RENDER_VULKAN = windows or linux,
        .SDL_VIDEO_RENDER_OGL = windows or linux,
        .SDL_VIDEO_RENDER_OGL_ES2 = windows or linux,
        .SDL_VIDEO_RENDER_PS2 = false,
        .SDL_VIDEO_RENDER_PSP = false,
        .SDL_VIDEO_RENDER_VITA_GXM = false,
        .SDL_VIDEO_OPENGL = windows or linux,
        .SDL_VIDEO_OPENGL_ES = linux,
        .SDL_VIDEO_OPENGL_ES2 = windows or linux,
        .SDL_VIDEO_OPENGL_BGL = false,
        .SDL_VIDEO_OPENGL_CGL = false,
        .SDL_VIDEO_OPENGL_GLX = linux,
        .SDL_VIDEO_OPENGL_WGL = windows,
        .SDL_VIDEO_OPENGL_EGL = windows or linux,
        .SDL_VIDEO_OPENGL_OSMESA = false,
        .SDL_VIDEO_OPENGL_OSMESA_DYNAMIC = "",
        .SDL_VIDEO_VULKAN = windows or linux,
        .SDL_VIDEO_METAL = false,
        .SDL_POWER_ANDROID = false,
        .SDL_POWER_LINUX = linux,
        .SDL_POWER_WINDOWS = windows,
        .SDL_POWER_WINRT = false,
        .SDL_POWER_MACOSX = false,
        .SDL_POWER_UIKIT = false,
        .SDL_POWER_HAIKU = false,
        .SDL_POWER_EMSCRIPTEN = false,
        .SDL_POWER_HARDWIRED = false,
        .SDL_POWER_VITA = false,
        .SDL_POWER_PSP = false,
        .SDL_POWER_N3DS = false,
        .SDL_FILESYSTEM_ANDROID = false,
        .SDL_FILESYSTEM_HAIKU = false,
        .SDL_FILESYSTEM_COCOA = false,
        .SDL_FILESYSTEM_DUMMY = false,
        .SDL_FILESYSTEM_RISCOS = false,
        .SDL_FILESYSTEM_UNIX = linux,
        .SDL_FILESYSTEM_WINDOWS = windows,
        .SDL_FILESYSTEM_EMSCRIPTEN = false,
        .SDL_FILESYSTEM_VITA = false,
        .SDL_FILESYSTEM_PSP = false,
        .SDL_FILESYSTEM_PS2 = false,
        .SDL_FILESYSTEM_N3DS = false,
        .SDL_STORAGE_GENERIC = windows or linux,
        .SDL_STORAGE_STEAM = windows or linux,
        .SDL_FSOPS_POSIX = linux,
        .SDL_FSOPS_WINDOWS = windows,
        .SDL_FSOPS_DUMMY = false,
        .SDL_CAMERA_DRIVER_DUMMY = windows or linux,
        .SDL_CAMERA_DRIVER_DISK = false,
        .SDL_CAMERA_DRIVER_V4L2 = linux,
        .SDL_CAMERA_DRIVER_COREMEDIA = false,
        .SDL_CAMERA_DRIVER_ANDROID = false,
        .SDL_CAMERA_DRIVER_EMSCRIPTEN = false,
        .SDL_CAMERA_DRIVER_MEDIAFOUNDATION = windows,
        .SDL_MISC_DUMMY = false,
        .SDL_LOCALE_DUMMY = false,
        .SDL_ALTIVEC_BLITTERS = false,
        .SDL_ARM_SIMD_BLITTERS = false,
        .SDL_ARM_NEON_BLITTERS = false,
        .DYNAPI_NEEDS_DLOPEN = linux,
        .SDL_USE_IME = linux,
        .SDL_IPHONE_KEYBOARD = false,
        .SDL_IPHONE_LAUNCHSCREEN = false,
        .SDL_VIDEO_VITA_PIB = false,
        .SDL_VIDEO_VITA_PVR = false,
        .SDL_VIDEO_VITA_PVR_OGL = false,
        .SDL_LIBDECOR_VERSION_MAJOR = if (linux) @as(u8, @intCast(cross_deps.libdecor_version.major)) else null,
        .SDL_LIBDECOR_VERSION_MINOR = if (linux) @as(u8, @intCast(cross_deps.libdecor_version.minor)) else null,
        .SDL_LIBDECOR_VERSION_PATCH = if (linux) @as(u8, @intCast(cross_deps.libdecor_version.patch)) else null,
        .SDL_DISABLE_SSE = !(x86 and std.Target.x86.featureSetHas(cpu.features, .sse)),
        .SDL_DISABLE_SSE2 = !(x86 and std.Target.x86.featureSetHas(cpu.features, .sse2)),
        .SDL_DISABLE_SSE3 = !(x86 and std.Target.x86.featureSetHas(cpu.features, .sse3)),
        .SDL_DISABLE_SSE4_1 = !(x86 and std.Target.x86.featureSetHas(cpu.features, .sse4_1)),
        .SDL_DISABLE_SSE4_2 = !(x86 and std.Target.x86.featureSetHas(cpu.features, .sse4_2)),
        .SDL_DISABLE_AVX = !(x86 and std.Target.x86.featureSetHas(cpu.features, .avx)),
        .SDL_DISABLE_AVX2 = !(x86 and std.Target.x86.featureSetHas(cpu.features, .avx2)),
        .SDL_DISABLE_AVX512F = !(x86 and std.Target.x86.featureSetHas(cpu.features, .avx512f)),
        .SDL_DISABLE_MMX = !(x86 and std.Target.x86.featureSetHas(cpu.features, .mmx)),
        .SDL_DISABLE_LSX = !(loongarch and std.Target.loongarch.featureSetHas(cpu.features, .lsx)),
        .SDL_DISABLE_LASX = !(loongarch and std.Target.loongarch.featureSetHas(cpu.features, .lasx)),
        .SDL_DISABLE_NEON = !(arm and std.Target.arm.featureSetHas(cpu.features, .neon) or aarch64 and std.Target.aarch64.featureSetHas(cpu.features, .neon)),
    });
}

fn addRevisionH(
    b: *std.Build,
    version: std.SemanticVersion,
) *std.Build.Step.ConfigHeader {
    return b.addConfigHeader(.{
        .style = .{ .cmake = b.path("include/build_config/SDL_revision.h.cmake") },
        .include_path = "SDL3/SDL_revision.h",
    }, .{
        .SDL_VENDOR_INFO = "https://github.com/castholm/SDL",
        .SDL_REVISION = b.fmt("SDL-{}", .{version}),
    });
}

const windows_c_files = [_][]const u8{
    "src/SDL.c",
    "src/SDL_assert.c",
    "src/SDL_error.c",
    "src/SDL_guid.c",
    "src/SDL_hashtable.c",
    "src/SDL_hints.c",
    "src/SDL_list.c",
    "src/SDL_log.c",
    "src/SDL_properties.c",
    "src/SDL_utils.c",
    "src/atomic/SDL_atomic.c",
    "src/atomic/SDL_spinlock.c",
    "src/audio/SDL_audio.c",
    "src/audio/SDL_audiocvt.c",
    "src/audio/SDL_audiodev.c",
    "src/audio/SDL_audioqueue.c",
    "src/audio/SDL_audioresample.c",
    "src/audio/SDL_audiotypecvt.c",
    "src/audio/SDL_mixer.c",
    "src/audio/SDL_wave.c",
    "src/camera/SDL_camera.c",
    "src/core/SDL_core_unsupported.c",
    "src/core/SDL_runapp.c",
    "src/cpuinfo/SDL_cpuinfo.c",
    "src/dynapi/SDL_dynapi.c",
    "src/events/SDL_clipboardevents.c",
    "src/events/SDL_displayevents.c",
    "src/events/SDL_dropevents.c",
    "src/events/SDL_events.c",
    "src/events/SDL_keyboard.c",
    "src/events/SDL_keysym_to_scancode.c",
    "src/events/SDL_mouse.c",
    "src/events/SDL_pen.c",
    "src/events/SDL_quit.c",
    "src/events/SDL_scancode_tables.c",
    "src/events/SDL_touch.c",
    "src/events/SDL_windowevents.c",
    "src/events/imKStoUCS.c",
    "src/file/SDL_iostream.c",
    "src/filesystem/SDL_filesystem.c",
    "src/haptic/SDL_haptic.c",
    "src/hidapi/SDL_hidapi.c",
    "src/joystick/SDL_gamepad.c",
    "src/joystick/SDL_joystick.c",
    "src/joystick/SDL_steam_virtual_gamepad.c",
    "src/joystick/controller_type.c",
    "src/libm/e_atan2.c",
    "src/libm/e_exp.c",
    "src/libm/e_fmod.c",
    "src/libm/e_log.c",
    "src/libm/e_log10.c",
    "src/libm/e_pow.c",
    "src/libm/e_rem_pio2.c",
    "src/libm/e_sqrt.c",
    "src/libm/k_cos.c",
    "src/libm/k_rem_pio2.c",
    "src/libm/k_sin.c",
    "src/libm/k_tan.c",
    "src/libm/s_atan.c",
    "src/libm/s_copysign.c",
    "src/libm/s_cos.c",
    "src/libm/s_fabs.c",
    "src/libm/s_floor.c",
    "src/libm/s_modf.c",
    "src/libm/s_scalbn.c",
    "src/libm/s_sin.c",
    "src/libm/s_tan.c",
    "src/locale/SDL_locale.c",
    "src/main/SDL_main_callbacks.c",
    "src/misc/SDL_url.c",
    "src/power/SDL_power.c",
    "src/render/SDL_d3dmath.c",
    "src/render/SDL_render.c",
    "src/render/SDL_render_unsupported.c",
    "src/render/SDL_yuv_sw.c",
    "src/render/direct3d/SDL_render_d3d.c",
    "src/render/direct3d/SDL_shaders_d3d.c",
    "src/render/direct3d11/SDL_render_d3d11.c",
    "src/render/direct3d11/SDL_shaders_d3d11.c",
    "src/render/direct3d12/SDL_render_d3d12.c",
    "src/render/direct3d12/SDL_shaders_d3d12.c",
    "src/render/opengl/SDL_render_gl.c",
    "src/render/opengl/SDL_shaders_gl.c",
    "src/render/opengles2/SDL_render_gles2.c",
    "src/render/opengles2/SDL_shaders_gles2.c",
    "src/render/ps2/SDL_render_ps2.c",
    "src/render/psp/SDL_render_psp.c",
    "src/render/software/SDL_blendfillrect.c",
    "src/render/software/SDL_blendline.c",
    "src/render/software/SDL_blendpoint.c",
    "src/render/software/SDL_drawline.c",
    "src/render/software/SDL_drawpoint.c",
    "src/render/software/SDL_render_sw.c",
    "src/render/software/SDL_rotate.c",
    "src/render/software/SDL_triangle.c",
    "src/render/vitagxm/SDL_render_vita_gxm.c",
    "src/render/vitagxm/SDL_render_vita_gxm_memory.c",
    "src/render/vitagxm/SDL_render_vita_gxm_tools.c",
    "src/render/vulkan/SDL_render_vulkan.c",
    "src/render/vulkan/SDL_shaders_vulkan.c",
    "src/sensor/SDL_sensor.c",
    "src/stdlib/SDL_crc16.c",
    "src/stdlib/SDL_crc32.c",
    "src/stdlib/SDL_getenv.c",
    "src/stdlib/SDL_iconv.c",
    "src/stdlib/SDL_malloc.c",
    "src/stdlib/SDL_memcpy.c",
    "src/stdlib/SDL_memmove.c",
    "src/stdlib/SDL_memset.c",
    "src/stdlib/SDL_mslibc.c",
    "src/stdlib/SDL_qsort.c",
    "src/stdlib/SDL_stdlib.c",
    "src/stdlib/SDL_string.c",
    "src/stdlib/SDL_strtokr.c",
    "src/storage/SDL_storage.c",
    "src/thread/SDL_thread.c",
    "src/time/SDL_time.c",
    "src/timer/SDL_timer.c",
    "src/video/SDL_RLEaccel.c",
    "src/video/SDL_blit.c",
    "src/video/SDL_blit_0.c",
    "src/video/SDL_blit_1.c",
    "src/video/SDL_blit_A.c",
    "src/video/SDL_blit_N.c",
    "src/video/SDL_blit_auto.c",
    "src/video/SDL_blit_copy.c",
    "src/video/SDL_blit_slow.c",
    "src/video/SDL_bmp.c",
    "src/video/SDL_clipboard.c",
    "src/video/SDL_egl.c",
    "src/video/SDL_fillrect.c",
    "src/video/SDL_pixels.c",
    "src/video/SDL_rect.c",
    "src/video/SDL_stretch.c",
    "src/video/SDL_surface.c",
    "src/video/SDL_video.c",
    "src/video/SDL_video_unsupported.c",
    "src/video/SDL_vulkan_utils.c",
    "src/video/SDL_yuv.c",
    "src/video/yuv2rgb/yuv_rgb_lsx.c",
    "src/video/yuv2rgb/yuv_rgb_sse.c",
    "src/video/yuv2rgb/yuv_rgb_std.c",
    "src/audio/dummy/SDL_dummyaudio.c",
    "src/audio/disk/SDL_diskaudio.c",
    "src/camera/dummy/SDL_camera_dummy.c",
    "src/joystick/virtual/SDL_virtualjoystick.c",
    "src/video/dummy/SDL_nullevents.c",
    "src/video/dummy/SDL_nullframebuffer.c",
    "src/video/dummy/SDL_nullvideo.c",
    "src/core/windows/SDL_hid.c",
    "src/core/windows/SDL_immdevice.c",
    "src/core/windows/SDL_windows.c",
    "src/core/windows/SDL_xinput.c",
    "src/core/windows/pch.c",
    "src/misc/windows/SDL_sysurl.c",
    "src/audio/directsound/SDL_directsound.c",
    "src/audio/wasapi/SDL_wasapi.c",
    "src/audio/wasapi/SDL_wasapi_win32.c",
    "src/video/windows/SDL_windowsclipboard.c",
    "src/video/windows/SDL_windowsevents.c",
    "src/video/windows/SDL_windowsframebuffer.c",
    "src/video/windows/SDL_windowskeyboard.c",
    "src/video/windows/SDL_windowsmessagebox.c",
    "src/video/windows/SDL_windowsmodes.c",
    "src/video/windows/SDL_windowsmouse.c",
    "src/video/windows/SDL_windowsopengl.c",
    "src/video/windows/SDL_windowsopengles.c",
    "src/video/windows/SDL_windowsrawinput.c",
    "src/video/windows/SDL_windowsshape.c",
    "src/video/windows/SDL_windowsvideo.c",
    "src/video/windows/SDL_windowsvulkan.c",
    "src/video/windows/SDL_windowswindow.c",
    "src/thread/generic/SDL_syscond.c",
    "src/thread/generic/SDL_sysrwlock.c",
    "src/thread/windows/SDL_syscond_cv.c",
    "src/thread/windows/SDL_sysmutex.c",
    "src/thread/windows/SDL_sysrwlock_srw.c",
    "src/thread/windows/SDL_syssem.c",
    "src/thread/windows/SDL_systhread.c",
    "src/thread/windows/SDL_systls.c",
    "src/sensor/windows/SDL_windowssensor.c",
    "src/power/windows/SDL_syspower.c",
    "src/locale/windows/SDL_syslocale.c",
    "src/filesystem/windows/SDL_sysfilesystem.c",
    "src/filesystem/windows/SDL_sysfsops.c",
    "src/storage/generic/SDL_genericstorage.c",
    "src/storage/steam/SDL_steamstorage.c",
    "src/time/windows/SDL_systime.c",
    "src/timer/windows/SDL_systimer.c",
    "src/loadso/windows/SDL_sysloadso.c",
    "src/core/windows/SDL_hid.c",
    "src/core/windows/SDL_immdevice.c",
    "src/core/windows/SDL_windows.c",
    "src/core/windows/SDL_xinput.c",
    "src/core/windows/pch.c",
    "src/joystick/hidapi/SDL_hidapi_combined.c",
    "src/joystick/hidapi/SDL_hidapi_gamecube.c",
    "src/joystick/hidapi/SDL_hidapi_luna.c",
    "src/joystick/hidapi/SDL_hidapi_ps3.c",
    "src/joystick/hidapi/SDL_hidapi_ps4.c",
    "src/joystick/hidapi/SDL_hidapi_ps5.c",
    "src/joystick/hidapi/SDL_hidapi_rumble.c",
    "src/joystick/hidapi/SDL_hidapi_shield.c",
    "src/joystick/hidapi/SDL_hidapi_stadia.c",
    "src/joystick/hidapi/SDL_hidapi_steam.c",
    "src/joystick/hidapi/SDL_hidapi_steamdeck.c",
    "src/joystick/hidapi/SDL_hidapi_switch.c",
    "src/joystick/hidapi/SDL_hidapi_wii.c",
    "src/joystick/hidapi/SDL_hidapi_xbox360.c",
    "src/joystick/hidapi/SDL_hidapi_xbox360w.c",
    "src/joystick/hidapi/SDL_hidapi_xboxone.c",
    "src/joystick/hidapi/SDL_hidapijoystick.c",
    "src/joystick/windows/SDL_dinputjoystick.c",
    "src/joystick/windows/SDL_rawinputjoystick.c",
    "src/joystick/windows/SDL_windows_gaming_input.c",
    "src/joystick/windows/SDL_windowsjoystick.c",
    "src/joystick/windows/SDL_xinputjoystick.c",
    "src/haptic/windows/SDL_dinputhaptic.c",
    "src/haptic/windows/SDL_windowshaptic.c",
    "src/camera/mediafoundation/SDL_camera_mediafoundation.c",
    "src/dialog/SDL_dialog_utils.c",
    "src/dialog/windows/SDL_windowsdialog.c",
    "src/video/offscreen/SDL_offscreenevents.c",
    "src/video/offscreen/SDL_offscreenframebuffer.c",
    "src/video/offscreen/SDL_offscreenopengles.c",
    "src/video/offscreen/SDL_offscreenvideo.c",
    "src/video/offscreen/SDL_offscreenwindow.c",
    "src/main/generic/SDL_sysmain_callbacks.c",
};

const linux_c_files = [_][]const u8{
    "src/SDL.c",
    "src/SDL_assert.c",
    "src/SDL_error.c",
    "src/SDL_guid.c",
    "src/SDL_hashtable.c",
    "src/SDL_hints.c",
    "src/SDL_list.c",
    "src/SDL_log.c",
    "src/SDL_properties.c",
    "src/SDL_utils.c",
    "src/atomic/SDL_atomic.c",
    "src/atomic/SDL_spinlock.c",
    "src/audio/SDL_audio.c",
    "src/audio/SDL_audiocvt.c",
    "src/audio/SDL_audiodev.c",
    "src/audio/SDL_audioqueue.c",
    "src/audio/SDL_audioresample.c",
    "src/audio/SDL_audiotypecvt.c",
    "src/audio/SDL_mixer.c",
    "src/audio/SDL_wave.c",
    "src/camera/SDL_camera.c",
    "src/core/SDL_core_unsupported.c",
    "src/core/SDL_runapp.c",
    "src/cpuinfo/SDL_cpuinfo.c",
    "src/dynapi/SDL_dynapi.c",
    "src/events/SDL_clipboardevents.c",
    "src/events/SDL_displayevents.c",
    "src/events/SDL_dropevents.c",
    "src/events/SDL_events.c",
    "src/events/SDL_keyboard.c",
    "src/events/SDL_keysym_to_scancode.c",
    "src/events/SDL_mouse.c",
    "src/events/SDL_pen.c",
    "src/events/SDL_quit.c",
    "src/events/SDL_scancode_tables.c",
    "src/events/SDL_touch.c",
    "src/events/SDL_windowevents.c",
    "src/events/imKStoUCS.c",
    "src/file/SDL_iostream.c",
    "src/filesystem/SDL_filesystem.c",
    "src/haptic/SDL_haptic.c",
    "src/hidapi/SDL_hidapi.c",
    "src/joystick/SDL_gamepad.c",
    "src/joystick/SDL_joystick.c",
    "src/joystick/SDL_steam_virtual_gamepad.c",
    "src/joystick/controller_type.c",
    "src/libm/e_atan2.c",
    "src/libm/e_exp.c",
    "src/libm/e_fmod.c",
    "src/libm/e_log.c",
    "src/libm/e_log10.c",
    "src/libm/e_pow.c",
    "src/libm/e_rem_pio2.c",
    "src/libm/e_sqrt.c",
    "src/libm/k_cos.c",
    "src/libm/k_rem_pio2.c",
    "src/libm/k_sin.c",
    "src/libm/k_tan.c",
    "src/libm/s_atan.c",
    "src/libm/s_copysign.c",
    "src/libm/s_cos.c",
    "src/libm/s_fabs.c",
    "src/libm/s_floor.c",
    "src/libm/s_modf.c",
    "src/libm/s_scalbn.c",
    "src/libm/s_sin.c",
    "src/libm/s_tan.c",
    "src/locale/SDL_locale.c",
    "src/main/SDL_main_callbacks.c",
    "src/misc/SDL_url.c",
    "src/power/SDL_power.c",
    "src/render/SDL_d3dmath.c",
    "src/render/SDL_render.c",
    "src/render/SDL_render_unsupported.c",
    "src/render/SDL_yuv_sw.c",
    "src/render/direct3d/SDL_render_d3d.c",
    "src/render/direct3d/SDL_shaders_d3d.c",
    "src/render/direct3d11/SDL_render_d3d11.c",
    "src/render/direct3d11/SDL_shaders_d3d11.c",
    "src/render/direct3d12/SDL_render_d3d12.c",
    "src/render/direct3d12/SDL_shaders_d3d12.c",
    "src/render/opengl/SDL_render_gl.c",
    "src/render/opengl/SDL_shaders_gl.c",
    "src/render/opengles2/SDL_render_gles2.c",
    "src/render/opengles2/SDL_shaders_gles2.c",
    "src/render/ps2/SDL_render_ps2.c",
    "src/render/psp/SDL_render_psp.c",
    "src/render/software/SDL_blendfillrect.c",
    "src/render/software/SDL_blendline.c",
    "src/render/software/SDL_blendpoint.c",
    "src/render/software/SDL_drawline.c",
    "src/render/software/SDL_drawpoint.c",
    "src/render/software/SDL_render_sw.c",
    "src/render/software/SDL_rotate.c",
    "src/render/software/SDL_triangle.c",
    "src/render/vitagxm/SDL_render_vita_gxm.c",
    "src/render/vitagxm/SDL_render_vita_gxm_memory.c",
    "src/render/vitagxm/SDL_render_vita_gxm_tools.c",
    "src/render/vulkan/SDL_render_vulkan.c",
    "src/render/vulkan/SDL_shaders_vulkan.c",
    "src/sensor/SDL_sensor.c",
    "src/stdlib/SDL_crc16.c",
    "src/stdlib/SDL_crc32.c",
    "src/stdlib/SDL_getenv.c",
    "src/stdlib/SDL_iconv.c",
    "src/stdlib/SDL_malloc.c",
    "src/stdlib/SDL_memcpy.c",
    "src/stdlib/SDL_memmove.c",
    "src/stdlib/SDL_memset.c",
    "src/stdlib/SDL_mslibc.c",
    "src/stdlib/SDL_qsort.c",
    "src/stdlib/SDL_stdlib.c",
    "src/stdlib/SDL_string.c",
    "src/stdlib/SDL_strtokr.c",
    "src/storage/SDL_storage.c",
    "src/thread/SDL_thread.c",
    "src/time/SDL_time.c",
    "src/timer/SDL_timer.c",
    "src/video/SDL_RLEaccel.c",
    "src/video/SDL_blit.c",
    "src/video/SDL_blit_0.c",
    "src/video/SDL_blit_1.c",
    "src/video/SDL_blit_A.c",
    "src/video/SDL_blit_N.c",
    "src/video/SDL_blit_auto.c",
    "src/video/SDL_blit_copy.c",
    "src/video/SDL_blit_slow.c",
    "src/video/SDL_bmp.c",
    "src/video/SDL_clipboard.c",
    "src/video/SDL_egl.c",
    "src/video/SDL_fillrect.c",
    "src/video/SDL_pixels.c",
    "src/video/SDL_rect.c",
    "src/video/SDL_stretch.c",
    "src/video/SDL_surface.c",
    "src/video/SDL_video.c",
    "src/video/SDL_video_unsupported.c",
    "src/video/SDL_vulkan_utils.c",
    "src/video/SDL_yuv.c",
    "src/video/yuv2rgb/yuv_rgb_lsx.c",
    "src/video/yuv2rgb/yuv_rgb_sse.c",
    "src/video/yuv2rgb/yuv_rgb_std.c",
    "src/audio/dummy/SDL_dummyaudio.c",
    "src/audio/disk/SDL_diskaudio.c",
    "src/camera/dummy/SDL_camera_dummy.c",
    "src/loadso/dlopen/SDL_sysloadso.c",
    "src/joystick/virtual/SDL_virtualjoystick.c",
    "src/video/dummy/SDL_nullevents.c",
    "src/video/dummy/SDL_nullframebuffer.c",
    "src/video/dummy/SDL_nullvideo.c",
    "src/audio/alsa/SDL_alsa_audio.c",
    "src/audio/jack/SDL_jackaudio.c",
    "src/audio/pipewire/SDL_pipewire.c",
    "src/audio/pulseaudio/SDL_pulseaudio.c",
    "src/audio/sndio/SDL_sndioaudio.c",
    "src/video/x11/SDL_x11clipboard.c",
    "src/video/x11/SDL_x11dyn.c",
    "src/video/x11/SDL_x11events.c",
    "src/video/x11/SDL_x11framebuffer.c",
    "src/video/x11/SDL_x11keyboard.c",
    "src/video/x11/SDL_x11messagebox.c",
    "src/video/x11/SDL_x11modes.c",
    "src/video/x11/SDL_x11mouse.c",
    "src/video/x11/SDL_x11opengl.c",
    "src/video/x11/SDL_x11opengles.c",
    "src/video/x11/SDL_x11pen.c",
    "src/video/x11/SDL_x11shape.c",
    "src/video/x11/SDL_x11touch.c",
    "src/video/x11/SDL_x11video.c",
    "src/video/x11/SDL_x11vulkan.c",
    "src/video/x11/SDL_x11window.c",
    "src/video/x11/SDL_x11xfixes.c",
    "src/video/x11/SDL_x11xinput2.c",
    "src/video/x11/edid-parse.c",
    "src/video/kmsdrm/SDL_kmsdrmdyn.c",
    "src/video/kmsdrm/SDL_kmsdrmevents.c",
    "src/video/kmsdrm/SDL_kmsdrmmouse.c",
    "src/video/kmsdrm/SDL_kmsdrmopengles.c",
    "src/video/kmsdrm/SDL_kmsdrmvideo.c",
    "src/video/kmsdrm/SDL_kmsdrmvulkan.c",
    "src/video/wayland/SDL_waylandclipboard.c",
    "src/video/wayland/SDL_waylanddatamanager.c",
    "src/video/wayland/SDL_waylanddyn.c",
    "src/video/wayland/SDL_waylandevents.c",
    "src/video/wayland/SDL_waylandkeyboard.c",
    "src/video/wayland/SDL_waylandmessagebox.c",
    "src/video/wayland/SDL_waylandmouse.c",
    "src/video/wayland/SDL_waylandopengles.c",
    "src/video/wayland/SDL_waylandshmbuffer.c",
    "src/video/wayland/SDL_waylandvideo.c",
    "src/video/wayland/SDL_waylandvulkan.c",
    "src/video/wayland/SDL_waylandwindow.c",
    "src/core/unix/SDL_appid.c",
    "src/core/unix/SDL_poll.c",
    "src/camera/v4l2/SDL_camera_v4l2.c",
    "src/haptic/linux/SDL_syshaptic.c",
    "src/core/linux/SDL_dbus.c",
    "src/core/linux/SDL_system_theme.c",
    "src/core/linux/SDL_ime.c",
    "src/core/linux/SDL_ibus.c",
    "src/core/linux/SDL_fcitx.c",
    "src/core/linux/SDL_udev.c",
    "src/core/linux/SDL_evdev.c",
    "src/core/linux/SDL_evdev_kbd.c",
    "src/core/linux/SDL_evdev_capabilities.c",
    "src/core/linux/SDL_threadprio.c",
    "src/core/linux/SDL_sandbox.c",
    "src/joystick/hidapi/SDL_hidapi_combined.c",
    "src/joystick/hidapi/SDL_hidapi_gamecube.c",
    "src/joystick/hidapi/SDL_hidapi_luna.c",
    "src/joystick/hidapi/SDL_hidapi_ps3.c",
    "src/joystick/hidapi/SDL_hidapi_ps4.c",
    "src/joystick/hidapi/SDL_hidapi_ps5.c",
    "src/joystick/hidapi/SDL_hidapi_rumble.c",
    "src/joystick/hidapi/SDL_hidapi_shield.c",
    "src/joystick/hidapi/SDL_hidapi_stadia.c",
    "src/joystick/hidapi/SDL_hidapi_steam.c",
    "src/joystick/hidapi/SDL_hidapi_steamdeck.c",
    "src/joystick/hidapi/SDL_hidapi_switch.c",
    "src/joystick/hidapi/SDL_hidapi_wii.c",
    "src/joystick/hidapi/SDL_hidapi_xbox360.c",
    "src/joystick/hidapi/SDL_hidapi_xbox360w.c",
    "src/joystick/hidapi/SDL_hidapi_xboxone.c",
    "src/joystick/hidapi/SDL_hidapijoystick.c",
    "src/joystick/linux/SDL_sysjoystick.c",
    "src/joystick/steam/SDL_steamcontroller.c",
    "src/thread/pthread/SDL_systhread.c",
    "src/thread/pthread/SDL_sysmutex.c",
    "src/thread/pthread/SDL_syscond.c",
    "src/thread/pthread/SDL_sysrwlock.c",
    "src/thread/pthread/SDL_systls.c",
    "src/thread/pthread/SDL_syssem.c",
    "src/misc/unix/SDL_sysurl.c",
    "src/power/linux/SDL_syspower.c",
    "src/locale/unix/SDL_syslocale.c",
    "src/filesystem/unix/SDL_sysfilesystem.c",
    "src/storage/generic/SDL_genericstorage.c",
    "src/storage/steam/SDL_steamstorage.c",
    "src/filesystem/posix/SDL_sysfsops.c",
    "src/time/unix/SDL_systime.c",
    "src/timer/unix/SDL_systimer.c",
    "src/dialog/SDL_dialog_utils.c",
    "src/dialog/unix/SDL_unixdialog.c",
    "src/dialog/unix/SDL_portaldialog.c",
    "src/dialog/unix/SDL_zenitydialog.c",
    "src/video/offscreen/SDL_offscreenevents.c",
    "src/video/offscreen/SDL_offscreenframebuffer.c",
    "src/video/offscreen/SDL_offscreenopengles.c",
    "src/video/offscreen/SDL_offscreenvideo.c",
    "src/video/offscreen/SDL_offscreenwindow.c",
    "src/sensor/dummy/SDL_dummysensor.c",
    "src/main/generic/SDL_sysmain_callbacks.c",
};

const c_flags = [_][]const u8{
    "-std=c99",
    "-gdwarf-4",
    "-Wall",
    "-Wundef",
    "-fno-strict-aliasing",
    "-Wdocumentation",
    "-Wdocumentation-unknown-command",
    "-fcomment-block-commands=threadsafety",
    "-Wshadow",
    "-Wno-unused-local-typedefs",
    "-Wimplicit-fallthrough",
    "-fcolor-diagnostics",
};

// TODO Prefix with 'SDL3/' when path comparison bug is fixed
const installed_headers = [_][]const u8{
    "SDL.h",
    "SDL_assert.h",
    "SDL_atomic.h",
    "SDL_audio.h",
    "SDL_begin_code.h",
    "SDL_bits.h",
    "SDL_blendmode.h",
    "SDL_camera.h",
    "SDL_clipboard.h",
    "SDL_close_code.h",
    "SDL_copying.h",
    "SDL_cpuinfo.h",
    "SDL_dialog.h",
    "SDL_egl.h",
    "SDL_endian.h",
    "SDL_error.h",
    "SDL_events.h",
    "SDL_filesystem.h",
    "SDL_gamepad.h",
    "SDL_guid.h",
    "SDL_haptic.h",
    "SDL_hidapi.h",
    "SDL_hints.h",
    "SDL_init.h",
    "SDL_intrin.h",
    "SDL_iostream.h",
    "SDL_joystick.h",
    "SDL_keyboard.h",
    "SDL_keycode.h",
    "SDL_loadso.h",
    "SDL_locale.h",
    "SDL_log.h",
    "SDL_main_impl.h",
    "SDL_main.h",
    "SDL_messagebox.h",
    "SDL_metal.h",
    "SDL_misc.h",
    "SDL_mouse.h",
    "SDL_mutex.h",
    "SDL_oldnames.h",
    "SDL_opengl_glext.h",
    "SDL_opengl.h",
    "SDL_opengles.h",
    "SDL_opengles2_gl2.h",
    "SDL_opengles2_gl2ext.h",
    "SDL_opengles2_gl2platform.h",
    "SDL_opengles2_khrplatform.h",
    "SDL_opengles2.h",
    "SDL_pen.h",
    "SDL_pixels.h",
    "SDL_platform_defines.h",
    "SDL_platform.h",
    "SDL_power.h",
    "SDL_properties.h",
    "SDL_rect.h",
    "SDL_render.h",
    "SDL_scancode.h",
    "SDL_sensor.h",
    "SDL_stdinc.h",
    "SDL_storage.h",
    "SDL_surface.h",
    "SDL_system.h",
    "SDL_thread.h",
    "SDL_time.h",
    "SDL_timer.h",
    "SDL_touch.h",
    "SDL_version.h",
    "SDL_video.h",
    "SDL_vulkan.h",
};
